### PR TITLE
I created some minimalistic styling for your website.

### PR DESCRIPTION
**Pull request by delirious44**

### CODE REVIEW

**Comment by delirious44** [comment]
I thought Id help you with some styling

**Comment by deatcoca** [comment]
Thank you very much for your contribution! It is greatly appreciated, it's the first time that someone contribute to one of my projects. I like the new styling of the website, you did a good job.
The problem is that this is a school project, so I don't know if I can accept your contribution. I will talk with my teammate and I will let you know if I can accept it here. 
(How did you find this repo by the way ? :eyes: )

**Comment by delirious44** [comment]
@deatcoca Ah sorry, I didnt know that. I was exploring website repos that are being developed and just saw this repo which I thought might need some help, I checked it and I saw that you needed a bit of styling and decided to help you out. :D I wanted to ask you first because I though you had plans for yourself to style it but couldnt find you anywhere so I just opened an issue and a pull request.. (Why so cryptive?)

**Comment by deatcoca** [comment]
I talked with my teammate and she's okay with that. I will merge your pull request 😄 Thank you very much for your help @delirious44 !

**Comment by delirious44** [comment]
No need for thanks, I will continue to look out for your project and if there is something to contribute for the layout / overall design that you would be satisfied with and would meet your criterias as specified in your contributor.md then I`ll gladly help again. I hope you rock the school thing you got going on :P

**Pull request merged**
